name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels: ["feature", "enhancement"]
  - title: "🐛 Fixes"
    labels: ["fix", "bug"]
  - title: "🧰 Maintenance"
    labels: ["chore", "docs", "refactor"]
change-template: "- $TITLE (#$NUMBER)"
version-resolver:
  minor:
    labels:
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "fix"
      - "bug"
  default: patch
template: |
  ## Changes

  $CHANGES
