import { Buffer } from 'node:buffer';

export function createBase64ImageBuffer(): Buffer {
  const jpegB64 =
    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAQEBAQEA8QDw8QDw8QEA8PDw8QFREWFhURFRUYHSggGBolGxUVITEhJSkrLi4uFx8zODMtNygtLisBCgoKDg0OGhAQGi0lHyUtLS0tLS0tLS8tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAAEAAQMBIgACEQEDEQH/xAAXAAADAQAAAAAAAAAAAAAAAAAFBAYB/8QAHxAAAQQCAwAAAAAAAAAAAAAAAgABAxEEEiExQXHB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAXEQEBAQEAAAAAAAAAAAAAAAAAAQIh/9oADAMBAAIRAxEAPwD0QK2CwBmAGYAGYAGfVwN0zv4b5a6v0W7mclR1VgZs7o9nqR5gJ8m0lZTXHc+1xGdF8iVQv//Z';
  return Buffer.from(jpegB64, 'base64');
}
