name: Run WordPress Plugin Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_tests
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, mysqli
          ini-values: memory_limit=-1
          tools: phpunit

      - name: Install WP Test Suite
        run: |
          bash ./tests/bin/install-wp-tests.sh wordpress_tests root root 127.0.0.1 latest

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-text
