name: Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    env:
      DB_NAME: wp_phpunit_tests
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: 127.0.0.1
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        php: ['8.1']
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, mysqli, gd, intl, zip
          tools: composer:v2
          coverage: none

      - name: Ensure Composer auth present
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "::error ::Composer auth missing. Add GITHUB_TOKEN (or set Composer OAuth locally)."
            echo "Docs: README -> Composer auth section."
            exit 1
          fi

      # Give Composer GitHub auth so it won't rate-limit
      - name: Configure Composer GitHub OAuth
        run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Create test database
        run: mysql -h "$DB_HOST" -u"$DB_USER" -p"$DB_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

      - name: Run unit tests
        run: composer test:unit

      - name: Run integration tests
        run: composer test:int

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, gd, intl, zip
          tools: composer:v2
          coverage: none

      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Ensure Composer auth present
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "::error ::Composer auth missing. Add GITHUB_TOKEN (or set Composer OAuth locally)."
            echo "Docs: README -> Composer auth section."
            exit 1
          fi

      - name: Configure Composer GitHub OAuth
        run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Composer (for wp-cli/wp-env deps if needed)
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install PHP deps for tooling
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Install npm deps
        run: npm ci

      - name: Start wp-env (port 8888)
        run: npx wp-env start

      - name: Install Playwright browsers
        run: npx --yes @playwright/test install --with-deps

      - name: Run Playwright smoke tests
        run: WP_BASE_URL=http://localhost:8888 npm run test:e2e

      - name: Stop wp-env
        if: always()
        run: npx wp-env stop
